<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="a_SRP.cs" />
    <Compile Remove="b_OCP.cs" />
    <Compile Remove="c_LSP.cs" />
    <Compile Remove="d_ISP.cs" />
    <Compile Remove="e_DIP.cs" />
    <Compile Remove="Program.cs" />
  </ItemGroup>

  <ItemGroup>
    <None Include="b_OCP.cs" />
    <None Include="c_LSP.cs" />
    <None Include="d_ISP.cs" />
    <None Include="e_DIP.cs" />
    <None Include="Program.cs" />
    <None Include="a_SRP.cs" />
  </ItemGroup>

</Project>
